I solved problems in third lab
iceandrise/bountydo pull request #2
Opened 2022-04-04 13:40 UTC by iceandrise

You wrote me some problems of my lab in this repo: https://github.com/iceandrise/itirod2/pull/2
Waiting for your mark or comments.

2022-04-11 14:00 UTC, katetushkan requested changes
deploy link?

2022-04-11 14:00 UTC, katetushkan commented on index.html
> +        <a class = "auth_buttons" href="index.html">
not solved.

2022-04-11 14:00 UTC, katetushkan commented on index.html
> +              <span class="wrapper__counter_completed">Completed tasks:</span>
not solved. should be `<p>`

2022-04-11 14:00 UTC, katetushkan commented on index.html
> +            <h1 class="tagfilter__title">Tag filter</h1>
not solved. https://github.com/iceandrise/itirod2/pull/2#discussion_r841498032
It's related to everything.

2022-04-11 14:00 UTC, katetushkan commented on index.html
> +              <span class="wrapper__output_count">Count of your pets:</span>
should be `<p>`

2022-04-11 14:00 UTC, katetushkan commented on logout.html
> +            <a  class = "auth_buttons" href="signin.html">
same here https://github.com/iceandrise/itirod2/pull/2#discussion_r841495151

2022-04-11 14:00 UTC, katetushkan commented on signin.css
> +    background-color:forestgreen;
when I told css variables I meant [this](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).

2022-04-11 14:00 UTC, katetushkan commented on signup.css
> +     .main {
fix tabs

2022-04-11 14:00 UTC, katetushkan commented on signup.css
> +  .main input[type=text], input[type=username] {
use class names

2022-04-12 13:15 UTC, iceandrise commented on logout.html
> +            <a  class = "auth_buttons" href="signin.html">
Sorry, but I don't understand my mistake... Can you explain more?

2022-04-21 20:19 UTC, iceandrise commented
@katetushkan  could you review please?

2022-04-21 20:22 UTC, katetushkan requested changes

2022-04-21 20:22 UTC, katetushkan commented on README.md
> +*Курилович Карина 953504*
<img width="327" alt="Screenshot 2022-04-21 at 21 22 12" src="https://user-images.githubusercontent.com/43992068/164546179-45127fbd-40e7-4c3f-8b0f-b68cce401fcb.png">
It still doesn't have a mobile version.

2022-05-08 11:17 UTC, katetushkan commented
<img width="423" alt="image" src="https://user-images.githubusercontent.com/43992068/167293729-72497be0-813f-41da-8775-5ab29649aede.png">

Still no mobile version

2022-05-08 11:18 UTC, katetushkan requested changes
<img width="423" alt="image" src="https://user-images.githubusercontent.com/43992068/167293759-b35b549d-a6c9-44bb-aade-667a385b7d32.png">

Still no mobile version

2022-05-08 12:25 UTC, iceandrise commented
@katetushkan sorry, I updated deploy [link](https://6277b5c40f4e573efb2aa87c--classy-lolly-eece77.netlify.app/), please check

2022-05-08 12:29 UTC, iceandrise commented
@katetushkan also signin and signup pages will be remove at lab 5.

2022-05-08 15:03 UTC, katetushkan approved these changes
Okay. Then it's a <kbd>8</kbd>.

2022-05-15 21:00 UTC, merged